### ISSUE TITLE
What else do you think CosPlace can improve?

### ISSUE THREAD

**Issue by wpumain** [gmberton/CosPlace#23]
CosPlace  is a great work.In the article, you mentioned that it has two limitations. One is that the data must have an angle, and the other is that it does not perform well in small data sets。Does it have any other shortcomings? Or what can be improved in combination with the latest development of CV?

**Comment by gmberton** [comment]
Those are two shortcomings with respect to other methods, but I don't think they are big limitations, because
1) angle is easy to obtain, as IMUs have become quite cheap;
2) training on small datasets is not really an issue, because small scale geolocalization does not make too much sense (at least when the threshold is 25 meters).
Also, CosPlace performs (evalutaion) very well on small datasets, just it is not suitable for _training_ on small datasets.
I think the most important dimensions to improve are recall, descriptors dimension (the smaller the better), training speed and scalability.

**Comment by wpumain** [comment]
Think you for your help!
