### ISSUE TITLE
Image rotation in augmentations

### ISSUE THREAD

**Issue by Danessely** [gmberton/CosPlace#30]
Why didn't you use image rotation in the augmentations? Does it affect the metrics much?

**Comment by gmberton** [comment]
We wanted to make sure that our improvements over previous SOTA are due to the method, not to better augmentation, so we used the same augmentation as SFRS.
I'm quite confident that using better augmentations would improve the results, although we did not perform an ablation on that, as it was not the focus of the paper.
Things like tuning the parameters to the color jittering, adding slight rotations, applying a perspective transformation and random erasing are likely to improve the results

**Comment by Danessely** [comment]
Thanks for the reply!
