### ISSUE TITLE
ViT trained models

### ISSUE THREAD

**Issue by oravus** [gmberton/CosPlace#33]
Hi @gmberton, are ViT backbone models available somewhere to download?

**Comment by gmberton** [comment]
Hi @oravus, they are not online because with the code only CNN backbones are available (having ViT and CCT was making the code a bit messy). If you want I can pass them to you somehow, but you will need to adjust the `cosplace_network.py` by yourself because the current version does not support ViT. Let me know, I could upload it temporarily to a GDrive (it's about 330MB).

**Comment by oravus** [comment]
Thanks, @gmberton. A Gdrive link would be great, I can edit the `cosplace_network.py` accordingly (guessing [vgbench](https://github.com/gmberton/deep-visual-geo-localization-benchmark) would be helpful for this).

**Comment by gmberton** [comment]
This is the link to the trained ViT model which I uploaded to GDrive. Let me know when you download it so I'll delete it from there
https://drive.google.com/file/d/1yvUhCjCb47ygV6ev3z1g6pJF3Wb_I0K9/view?usp=sharing

**Comment by oravus** [comment]
Done, many thanks! :)
