### ISSUE TITLE
Question about coordinate system

### ISSUE THREAD

**Issue by YangSooRim** [gmberton/CosPlace#7]
Hello.
Thank you for your efforts.
I saw in the code 'test_dataset.py' that the coordinate system should be 'utm'.
If my own dataset is geo-tagged with 'gps(lat, lng)' do I need to convert the value to the utm coordinate system?

**Comment by gmberton** [comment]
Yes, UTM coordinates are needed while GPS is not suitable. This is because given two points A and B, a distance of 1 unit in UTM is equivalent to a distance of 1 meter, regardless of where A and B are located, so it is easy to measure distances between two points. On the other hand when using GPS it is more complicated to measure distances.
You can convert GPS to UTM simply like this using [the UTM library](https://pypi.org/project/utm/)
```
import utm
utm_east, utm_north, _, _ = utm.from_latlon(lat, lon)
```
